import styles from '../doc.module.css'

export function DocHowFormWorks() {
  return (
    <section id="how-form-works" className={styles.section}>
      <hr className={styles.hr} />
      <h2 className={styles.h2}>How the form works</h2>
      <p className={styles.p}>
        The reporting form is divided into two parts. The first part collects structured contextual information:
        the nature of the incident, where and when it occurred, whether there were witnesses, and the reporter's
        identity (or anonymity preference). These fields use dropdowns and short text inputs — they are quick to
        complete and feed directly into the AI pipeline as supporting context.
      </p>
      <p className={styles.p}>
        The second part is the <strong>Full Details section</strong> — the heart of the form, and where
        ClearPath's AI does its work. It contains three sub-questions, each serving a distinct purpose.
      </p>

      <div className={styles.stepFlow}>
        <div className={styles.stepPill}>
          <span className={styles.stepNum}>Q1</span>
          Reporter narrative
        </div>
        <span className={styles.stepArrow}>→</span>
        <div className={styles.stepPill}>
          <span className={`${styles.stepNum} ${styles.stepNumAI}`}>AI</span>
          Gap detection
        </div>
        <span className={styles.stepArrow}>→</span>
        <div className={styles.stepPill}>
          <span className={styles.stepNum}>Q2</span>
          Targeted follow-up
        </div>
        <span className={styles.stepArrow}>→</span>
        <div className={styles.stepPill}>
          <span className={`${styles.stepNum} ${styles.stepNumAI}`}>AI</span>
          Policy search
        </div>
        <span className={styles.stepArrow}>→</span>
        <div className={styles.stepPill}>
          <span className={styles.stepNum}>Q3</span>
          Policy question
        </div>
        <span className={styles.stepArrow}>→</span>
        <div className={styles.stepPill}>
          <span className={`${styles.stepNum} ${styles.stepNumGreen}`}>✓</span>
          Submit
        </div>
      </div>

      <p className={styles.p}>
        Each step is generated by — or informed by — what came before it. The form is not static: it reads the
        reporter's narrative and responds to it.
      </p>
    </section>
  )
}
